services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    environment:
      SA_PASSWORD: "BudgetFlow123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  budgetflow-api:
    build:
      context: .
      dockerfile: src/BudgetFlow.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BudgetFlowDb;User Id=sa;Password=BudgetFlow123!;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Key=BudgetFlowSuperSecretKey2024MustBe32Chars!
      - Jwt__Issuer=BudgetFlow
      - Jwt__Audience=BudgetFlowUsers
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis

volumes:
  sqlserver-data:
